name: ci_linux

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The final 1 indicates that we want to run this test on Tuesdays, making
    # this a weekly test.
    - cron:  '30 2 * * 1'
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install style
      run: |
        rustup component add rustfmt
    - uses: actions/checkout@v3
    - name: Style
      run: |
        cd sdformat_rs && cargo fmt --check
    - name: Build workspace
      run: |
        cd sdformat_rs && cargo build
    - name: Run tests
      run: |
        cd sdformat_rs && cargo test
